(ns gen-reflect-config
  "Generate reflect-config.json for Crema native image.
   Based on babashka's impl/classes.clj coverage."
  (:require [cheshire.core :as json]
            [clojure.java.io :as io]))

;; Java classes to register for reflection, based on babashka's class list.
;; For Crema, we need allPublicMethods + allPublicConstructors so the
;; interpreter can dispatch to compiled methods.
(def classes
  [;; java.io
   "java.io.BufferedInputStream"
   "java.io.BufferedOutputStream"
   "java.io.BufferedReader"
   "java.io.BufferedWriter"
   "java.io.ByteArrayInputStream"
   "java.io.ByteArrayOutputStream"
   "java.io.Closeable"
   "java.io.Console"
   "java.io.DataInput"
   "java.io.DataInputStream"
   "java.io.DataOutput"
   "java.io.DataOutputStream"
   "java.io.EOFException"
   "java.io.File"
   "java.io.FileFilter"
   "java.io.FileInputStream"
   "java.io.FilenameFilter"
   "java.io.FileNotFoundException"
   "java.io.FileOutputStream"
   "java.io.FileReader"
   "java.io.FileWriter"
   "java.io.Flushable"
   "java.io.InputStream"
   "java.io.InputStreamReader"
   "java.io.IOException"
   "java.io.LineNumberReader"
   "java.io.OutputStream"
   "java.io.OutputStreamWriter"
   "java.io.PipedInputStream"
   "java.io.PipedOutputStream"
   "java.io.PrintStream"
   "java.io.PrintWriter"
   "java.io.PushbackInputStream"
   "java.io.PushbackReader"
   "java.io.RandomAccessFile"
   "java.io.Reader"
   "java.io.SequenceInputStream"
   "java.io.StringReader"
   "java.io.StringWriter"
   "java.io.Writer"
   ;; java.lang
   "java.lang.AbstractMethodError"
   "java.lang.Appendable"
   "java.lang.ArithmeticException"
   "java.lang.AssertionError"
   "java.lang.AutoCloseable"
   "java.lang.Boolean"
   "java.lang.Byte"
   "java.lang.Character"
   "java.lang.Character$UnicodeBlock"
   "java.lang.CharSequence"
   "java.lang.Class"
   "java.lang.ClassCastException"
   "java.lang.ClassLoader"
   "java.lang.ClassNotFoundException"
   "java.lang.Comparable"
   "java.lang.Double"
   "java.lang.Error"
   "java.lang.Exception"
   "java.lang.ExceptionInInitializerError"
   "java.lang.Float"
   "java.lang.IllegalArgumentException"
   "java.lang.IllegalStateException"
   "java.lang.IndexOutOfBoundsException"
   "java.lang.Integer"
   "java.lang.InterruptedException"
   "java.lang.Iterable"
   "java.lang.LinkageError"
   "java.lang.Long"
   "java.lang.Math"
   "java.lang.NoSuchFieldException"
   "java.lang.NullPointerException"
   "java.lang.Number"
   "java.lang.NumberFormatException"
   "java.lang.Object"
   "java.lang.Package"
   "java.lang.Process"
   "java.lang.ProcessBuilder"
   "java.lang.ProcessBuilder$Redirect"
   "java.lang.ProcessHandle"
   "java.lang.ProcessHandle$Info"
   "java.lang.Runnable"
   "java.lang.Runtime"
   "java.lang.RuntimeException"
   "java.lang.SecurityException"
   "java.lang.Short"
   "java.lang.StackOverflowError"
   "java.lang.StackTraceElement"
   "java.lang.String"
   "java.lang.StringBuilder"
   "java.lang.System"
   "java.lang.Thread"
   "java.lang.Thread$UncaughtExceptionHandler"
   "java.lang.ThreadLocal"
   "java.lang.Throwable"
   "java.lang.UnsupportedOperationException"
   "java.lang.VirtualMachineError"
   ;; java.lang.invoke
   "java.lang.invoke.MethodHandle"
   "java.lang.invoke.MethodHandles"
   "java.lang.invoke.MethodHandles$Lookup"
   "java.lang.invoke.MethodType"
   ;; java.lang.ref
   "java.lang.ref.Cleaner"
   "java.lang.ref.ReferenceQueue"
   "java.lang.ref.SoftReference"
   "java.lang.ref.WeakReference"
   ;; java.lang.reflect
   "java.lang.reflect.AccessibleObject"
   "java.lang.reflect.Array"
   "java.lang.reflect.Constructor"
   "java.lang.reflect.Executable"
   "java.lang.reflect.Field"
   "java.lang.reflect.Member"
   "java.lang.reflect.Method"
   "java.lang.reflect.Modifier"
   ;; java.math
   "java.math.BigDecimal"
   "java.math.BigInteger"
   "java.math.MathContext"
   "java.math.RoundingMode"
   ;; java.net
   "java.net.Authenticator"
   "java.net.BindException"
   "java.net.ConnectException"
   "java.net.CookieHandler"
   "java.net.CookieManager"
   "java.net.CookiePolicy"
   "java.net.CookieStore"
   "java.net.DatagramPacket"
   "java.net.DatagramSocket"
   "java.net.HttpCookie"
   "java.net.HttpURLConnection"
   "java.net.Inet4Address"
   "java.net.Inet6Address"
   "java.net.InetAddress"
   "java.net.InetSocketAddress"
   "java.net.JarURLConnection"
   "java.net.PasswordAuthentication"
   "java.net.ProxySelector"
   "java.net.ServerSocket"
   "java.net.Socket"
   "java.net.SocketException"
   "java.net.SocketTimeoutException"
   "java.net.StandardProtocolFamily"
   "java.net.UnknownHostException"
   "java.net.URI"
   "java.net.URISyntaxException"
   "java.net.URL"
   "java.net.URLClassLoader"
   "java.net.URLConnection"
   "java.net.URLDecoder"
   "java.net.URLEncoder"
   ;; java.net.http
   "java.net.http.HttpClient"
   "java.net.http.HttpClient$Builder"
   "java.net.http.HttpClient$Redirect"
   "java.net.http.HttpClient$Version"
   "java.net.http.HttpHeaders"
   "java.net.http.HttpRequest"
   "java.net.http.HttpRequest$BodyPublisher"
   "java.net.http.HttpRequest$BodyPublishers"
   "java.net.http.HttpRequest$Builder"
   "java.net.http.HttpResponse"
   "java.net.http.HttpResponse$BodyHandler"
   "java.net.http.HttpResponse$BodyHandlers"
   "java.net.http.HttpTimeoutException"
   "java.net.http.WebSocket"
   "java.net.http.WebSocket$Builder"
   "java.net.http.WebSocket$Listener"
   ;; java.nio
   "java.nio.ByteBuffer"
   "java.nio.ByteOrder"
   "java.nio.CharBuffer"
   "java.nio.MappedByteBuffer"
   ;; java.nio.channels
   "java.nio.channels.ByteChannel"
   "java.nio.channels.Channels"
   "java.nio.channels.FileChannel"
   "java.nio.channels.FileChannel$MapMode"
   "java.nio.channels.ReadableByteChannel"
   "java.nio.channels.ServerSocketChannel"
   "java.nio.channels.SocketChannel"
   "java.nio.channels.WritableByteChannel"
   ;; java.nio.charset
   "java.nio.charset.CharacterCodingException"
   "java.nio.charset.Charset"
   "java.nio.charset.CharsetDecoder"
   "java.nio.charset.CharsetEncoder"
   "java.nio.charset.CoderResult"
   "java.nio.charset.CodingErrorAction"
   "java.nio.charset.StandardCharsets"
   ;; java.nio.file
   "java.nio.file.CopyOption"
   "java.nio.file.DirectoryNotEmptyException"
   "java.nio.file.DirectoryStream$Filter"
   "java.nio.file.FileAlreadyExistsException"
   "java.nio.file.Files"
   "java.nio.file.FileSystem"
   "java.nio.file.FileSystemNotFoundException"
   "java.nio.file.FileSystems"
   "java.nio.file.FileVisitOption"
   "java.nio.file.FileVisitor"
   "java.nio.file.FileVisitResult"
   "java.nio.file.LinkOption"
   "java.nio.file.NoSuchFileException"
   "java.nio.file.OpenOption"
   "java.nio.file.Path"
   "java.nio.file.PathMatcher"
   "java.nio.file.Paths"
   "java.nio.file.StandardCopyOption"
   "java.nio.file.StandardOpenOption"
   ;; java.nio.file.attribute
   "java.nio.file.attribute.BasicFileAttributes"
   "java.nio.file.attribute.FileAttribute"
   "java.nio.file.attribute.FileTime"
   "java.nio.file.attribute.GroupPrincipal"
   "java.nio.file.attribute.PosixFileAttributes"
   "java.nio.file.attribute.PosixFilePermission"
   "java.nio.file.attribute.PosixFilePermissions"
   "java.nio.file.attribute.UserDefinedFileAttributeView"
   "java.nio.file.attribute.UserPrincipal"
   ;; java.security
   "java.security.DigestInputStream"
   "java.security.DigestOutputStream"
   "java.security.Key"
   "java.security.KeyFactory"
   "java.security.KeyPair"
   "java.security.KeyPairGenerator"
   "java.security.KeyStore"
   "java.security.MessageDigest"
   "java.security.Provider"
   "java.security.SecureRandom"
   "java.security.Security"
   "java.security.Signature"
   "java.security.cert.CertificateFactory"
   "java.security.cert.X509Certificate"
   "java.security.spec.ECGenParameterSpec"
   "java.security.spec.PKCS8EncodedKeySpec"
   "java.security.spec.X509EncodedKeySpec"
   ;; java.sql
   "java.sql.Date"
   "java.sql.Timestamp"
   ;; java.text
   "java.text.BreakIterator"
   "java.text.Normalizer"
   "java.text.Normalizer$Form"
   "java.text.ParseException"
   "java.text.ParsePosition"
   "java.text.SimpleDateFormat"
   ;; java.time
   "java.time.Clock"
   "java.time.DateTimeException"
   "java.time.DayOfWeek"
   "java.time.Duration"
   "java.time.Instant"
   "java.time.LocalDate"
   "java.time.LocalDateTime"
   "java.time.LocalTime"
   "java.time.Month"
   "java.time.MonthDay"
   "java.time.OffsetDateTime"
   "java.time.OffsetTime"
   "java.time.Period"
   "java.time.Year"
   "java.time.YearMonth"
   "java.time.ZonedDateTime"
   "java.time.ZoneId"
   "java.time.ZoneOffset"
   ;; java.time.chrono
   "java.time.chrono.ChronoLocalDate"
   "java.time.chrono.ChronoLocalDateTime"
   "java.time.chrono.Chronology"
   "java.time.chrono.ChronoZonedDateTime"
   ;; java.time.format
   "java.time.format.DateTimeFormatter"
   "java.time.format.DateTimeFormatterBuilder"
   "java.time.format.DateTimeParseException"
   "java.time.format.DecimalStyle"
   "java.time.format.FormatStyle"
   "java.time.format.ResolverStyle"
   "java.time.format.SignStyle"
   "java.time.format.TextStyle"
   ;; java.time.temporal
   "java.time.temporal.ChronoField"
   "java.time.temporal.ChronoUnit"
   "java.time.temporal.IsoFields"
   "java.time.temporal.Temporal"
   "java.time.temporal.TemporalAccessor"
   "java.time.temporal.TemporalAdjuster"
   "java.time.temporal.TemporalAdjusters"
   "java.time.temporal.TemporalAmount"
   "java.time.temporal.TemporalField"
   "java.time.temporal.TemporalQuery"
   "java.time.temporal.TemporalUnit"
   "java.time.temporal.ValueRange"
   "java.time.temporal.WeekFields"
   ;; java.time.zone
   "java.time.zone.ZoneRules"
   ;; java.util
   "java.util.AbstractList"
   "java.util.AbstractMap"
   "java.util.AbstractSet"
   "java.util.ArrayDeque"
   "java.util.ArrayList"
   "java.util.Arrays"
   "java.util.Base64"
   "java.util.Base64$Decoder"
   "java.util.Base64$Encoder"
   "java.util.Collection"
   "java.util.Collections"
   "java.util.Comparator"
   "java.util.Date"
   "java.util.HashMap"
   "java.util.HashSet"
   "java.util.IdentityHashMap"
   "java.util.InputMismatchException"
   "java.util.Iterator"
   "java.util.LinkedHashSet"
   "java.util.LinkedList"
   "java.util.List"
   "java.util.Locale"
   "java.util.Map"
   "java.util.Map$Entry"
   "java.util.MissingResourceException"
   "java.util.NoSuchElementException"
   "java.util.Optional"
   "java.util.Properties"
   "java.util.Random"
   "java.util.ResourceBundle"
   "java.util.Scanner"
   "java.util.Set"
   "java.util.StringTokenizer"
   "java.util.TimeZone"
   "java.util.UUID"
   "java.util.WeakHashMap"
   ;; java.util.concurrent
   "java.util.concurrent.ArrayBlockingQueue"
   "java.util.concurrent.BlockingQueue"
   "java.util.concurrent.Callable"
   "java.util.concurrent.CancellationException"
   "java.util.concurrent.CompletableFuture"
   "java.util.concurrent.CompletionException"
   "java.util.concurrent.CompletionStage"
   "java.util.concurrent.ConcurrentHashMap"
   "java.util.concurrent.CountDownLatch"
   "java.util.concurrent.ExecutionException"
   "java.util.concurrent.Executor"
   "java.util.concurrent.Executors"
   "java.util.concurrent.ExecutorService"
   "java.util.concurrent.ForkJoinPool"
   "java.util.concurrent.Future"
   "java.util.concurrent.FutureTask"
   "java.util.concurrent.LinkedBlockingQueue"
   "java.util.concurrent.ScheduledExecutorService"
   "java.util.concurrent.ScheduledFuture"
   "java.util.concurrent.ScheduledThreadPoolExecutor"
   "java.util.concurrent.Semaphore"
   "java.util.concurrent.SynchronousQueue"
   "java.util.concurrent.ThreadFactory"
   "java.util.concurrent.ThreadLocalRandom"
   "java.util.concurrent.ThreadPoolExecutor"
   "java.util.concurrent.TimeoutException"
   "java.util.concurrent.TimeUnit"
   ;; java.util.concurrent.atomic
   "java.util.concurrent.atomic.AtomicInteger"
   "java.util.concurrent.atomic.AtomicLong"
   "java.util.concurrent.atomic.AtomicReference"
   ;; java.util.concurrent.locks
   "java.util.concurrent.locks.ReentrantLock"
   ;; java.util.function
   "java.util.function.BiConsumer"
   "java.util.function.BiFunction"
   "java.util.function.Consumer"
   "java.util.function.Function"
   "java.util.function.Predicate"
   "java.util.function.Supplier"
   ;; java.util.jar
   "java.util.jar.Attributes"
   "java.util.jar.Attributes$Name"
   "java.util.jar.JarEntry"
   "java.util.jar.JarFile"
   "java.util.jar.JarInputStream"
   "java.util.jar.JarOutputStream"
   "java.util.jar.Manifest"
   ;; java.util.regex
   "java.util.regex.Matcher"
   "java.util.regex.Pattern"
   "java.util.regex.PatternSyntaxException"
   ;; java.util.stream
   "java.util.stream.BaseStream"
   "java.util.stream.Collectors"
   "java.util.stream.IntStream"
   "java.util.stream.Stream"
   ;; java.util.zip
   "java.util.zip.CheckedInputStream"
   "java.util.zip.CRC32"
   "java.util.zip.Deflater"
   "java.util.zip.DeflaterInputStream"
   "java.util.zip.DeflaterOutputStream"
   "java.util.zip.GZIPInputStream"
   "java.util.zip.GZIPOutputStream"
   "java.util.zip.Inflater"
   "java.util.zip.InflaterInputStream"
   "java.util.zip.ZipEntry"
   "java.util.zip.ZipException"
   "java.util.zip.ZipFile"
   "java.util.zip.ZipInputStream"
   "java.util.zip.ZipOutputStream"
   ;; javax.crypto
   "javax.crypto.Cipher"
   "javax.crypto.KeyAgreement"
   "javax.crypto.Mac"
   "javax.crypto.SecretKey"
   "javax.crypto.SecretKeyFactory"
   "javax.crypto.spec.GCMParameterSpec"
   "javax.crypto.spec.IvParameterSpec"
   "javax.crypto.spec.PBEKeySpec"
   "javax.crypto.spec.SecretKeySpec"
   ;; javax.net.ssl
   "javax.net.ssl.HostnameVerifier"
   "javax.net.ssl.HttpsURLConnection"
   "javax.net.ssl.KeyManagerFactory"
   "javax.net.ssl.SSLContext"
   "javax.net.ssl.SSLException"
   "javax.net.ssl.SSLParameters"
   "javax.net.ssl.SSLSession"
   "javax.net.ssl.SSLSocket"
   "javax.net.ssl.SSLSocketFactory"
   "javax.net.ssl.TrustManager"
   "javax.net.ssl.TrustManagerFactory"
   "javax.net.ssl.X509ExtendedTrustManager"
   "javax.net.ssl.X509TrustManager"
   ;; javax.xml
   "javax.xml.namespace.QName"
   ;; Additional classes needed by Crema/Clojure runtime
   "javax.tools.JavaCompiler$CompilationTask"
   "com.sun.tools.javac.api.JavacTrees"
   ;; clojure.lang - needed for Crema interpreter dispatch
   "clojure.lang.AFn"
   "clojure.lang.AFunction"
   "clojure.lang.Agent"
   "clojure.lang.APersistentMap"
   "clojure.lang.APersistentSet"
   "clojure.lang.APersistentVector"
   "clojure.lang.ARef"
   "clojure.lang.ArityException"
   "clojure.lang.Associative"
   "clojure.lang.Atom"
   "clojure.lang.BigInt"
   "clojure.lang.Compiler"
   "clojure.lang.Cons"
   "clojure.lang.Counted"
   "clojure.lang.Delay"
   "clojure.lang.DynamicClassLoader"
   "clojure.lang.ExceptionInfo"
   "clojure.lang.IDeref"
   "clojure.lang.IEditableCollection"
   "clojure.lang.IFn"
   "clojure.lang.IHashEq"
   "clojure.lang.IKVReduce"
   "clojure.lang.ILookup"
   "clojure.lang.IMapEntry"
   "clojure.lang.IMeta"
   "clojure.lang.Indexed"
   "clojure.lang.IObj"
   "clojure.lang.IPersistentCollection"
   "clojure.lang.IPersistentList"
   "clojure.lang.IPersistentMap"
   "clojure.lang.IPersistentSet"
   "clojure.lang.IPersistentStack"
   "clojure.lang.IPersistentVector"
   "clojure.lang.IReduce"
   "clojure.lang.IReduceInit"
   "clojure.lang.IRef"
   "clojure.lang.ISeq"
   "clojure.lang.ITransientCollection"
   "clojure.lang.ITransientVector"
   "clojure.lang.Keyword"
   "clojure.lang.LazySeq"
   "clojure.lang.LongRange"
   "clojure.lang.MapEntry"
   "clojure.lang.MultiFn"
   "clojure.lang.Named"
   "clojure.lang.Namespace"
   "clojure.lang.PersistentArrayMap"
   "clojure.lang.PersistentHashMap"
   "clojure.lang.PersistentHashSet"
   "clojure.lang.PersistentList"
   "clojure.lang.PersistentQueue"
   "clojure.lang.PersistentTreeMap"
   "clojure.lang.PersistentTreeSet"
   "clojure.lang.PersistentVector"
   "clojure.lang.Range"
   "clojure.lang.Ratio"
   "clojure.lang.Ref"
   "clojure.lang.Reversible"
   "clojure.lang.RT"
   "clojure.lang.SeqIterator"
   "clojure.lang.Sequential"
   "clojure.lang.Sorted"
   "clojure.lang.Symbol"
   "clojure.lang.Var"
   "clojure.lang.Volatile"
   ;; Compiled Clojure function classes needed by #= reader macro.
   ;; core.async uses #=(clojure.core$apply) in compiled code.
   "clojure.core$apply"])

(defn generate []
  (let [entries (mapv (fn [class-name]
                        {"name" class-name
                         "allPublicMethods" true
                         "allPublicConstructors" true
                         "allPublicFields" true})
                      classes)]
    (spit "reflect-config.json"
          (json/generate-string entries {:pretty true}))
    (println "Generated reflect-config.json with" (count entries) "classes")))

(generate)
