name: Graal repro

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  repro:
    runs-on: [ windows-2022 ]

    defaults:
      run:
        shell: pwsh   # use PowerShell Core (recommended)
        # or: powershell   # if you want Windows PowerShell 5.1

    strategy:
      matrix:
        java: [25]  # OpenJDK versions
        distribution: [graalvm]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}

      - name: Print versions
        run: |
          java -version
          $PSVersionTable.PSVersion

      - name: Run in java
        run: |
          java Repro.java

      - name: native-image
        if: matrix.distribution == 'graalvm'
        run: |
          javac Repro.java
          native-image Repro --initialize-at-build-time=Repro

      - name: run native-image
        if: matrix.distribution == 'graalvm'
        run: |
          ./repro
