name: Graal repro

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  check-os-arch:
    runs-on: [ ubuntu-latest, windows-2022 ]

    strategy:
      matrix:
        java: [ 25 ]  # OpenJDK versions
        distribution: [ graalvm ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}

      - name: Print Java version
        run: java -version

      - name: Run java to print os.arch
        run: |
          java Repro.java
          echo '====='
          java -Djava.security.properties=java.security
          java Repro.java

      - name: native-image
        if: matrix.distribution == 'graalvm'
        run: |
          javac Repro.java
          native-image "--initialize-at-run-time=sun.security.ssl.SSLContextImpl,sun.security.ssl.SSLAlgorithmConstraints" Repro
          ./repro
          echo '====='
          ./repro -Djava.security.properties=java.security
