name: Check os.arch on macOS Intel

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  check-os-arch:
    runs-on: macos-13  # This is macOS Intel; macos-14 is Apple Silicon

    strategy:
      matrix:
        java: [21, 24, 25]  # OpenJDK versions
        distribution: [oracle, graalvm]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}

      - name: Print Java version
        run: java -version

      - name: Run java to print os.arch
        run: |
          java PrintArch.java
