name: Graal repro

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  check-os-arch:

    strategy:
      matrix:
        java: [ 25 ]  # OpenJDK versions
        distribution: [ graalvm ]
        os: [ ubuntu-latest, windows-2022 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}

      - name: Print Java version
        run: java -version

      - name: Run java to print os.arch
        run: |
          java Repro.java
          echo '====='
          java "-Djava.security.properties=java.security" Repro.java

      - name: native-image
        if: matrix.distribution == 'graalvm'
        run: |
          javac Repro.java
          native-image "--future-defaults=all" "--initialize-at-run-time=sun.security.ssl.SSLContextImpl,sun.security.ssl.SSLAlgorithmConstraints" -H:+AddAllCharsets Repro
          ./repro
          echo '====='
          ./repro "-Djava.security.properties=java.security"
