name: Check os.arch on macOS Intel

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  check-os-arch:
    runs-on: macos-13  # This is macOS Intel; macos-14 is Apple Silicon

    strategy:
      matrix:
        java: [24, 25]  # OpenJDK versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Print Java version
        run: java -version

      - name: Run Clojure to print os.arch
        run: |
          cat <<'EOF' > PrintArch.clj
          (println (System/getProperty "os.arch"))
          EOF
          clojure PrintArch.clj
