name: Graal repro

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  repro:
    runs-on: [ windows-2022 ]

    defaults:
      run:
        shell: pwsh   # use PowerShell Core (recommended)
        # or: powershell   # if you want Windows PowerShell 5.1

    strategy:
      matrix:
        java: [25]  # OpenJDK versions
        distribution: [graalvm]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}

      - name: Print versions
        run: |
          java -version
          $PSVersionTable.PSVersion

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          # Install just one or all simultaneously
          # The value must indicate a particular version of the tool, or use 'latest'
          # to always provision the latest version
          cli: latest
          bb: latest

      - name: Run in Clojure
        run: |
          clojure -T:build uber
          java -jar target/repro-1.0.0-standalone.jar

      - name: Native-image compile
        run: |
          native-image -jar target/repro-1.0.0-standalone.jar --initialize-at-build-time=clojure,my -o repro

      # - name: Run in java
      #   run: |
      #     java Repro.java

      # - name: native-image
      #   if: matrix.distribution == 'graalvm'
      #   run: |
      #     javac Repro.java
      #     native-image Repro --initialize-at-build-time=Repro --verbose

      - name: run native-image
        if: matrix.distribution == 'graalvm'
        run: |
          ./repro
          ./repro -Djava.file.encoding=UTF-8
          $OutputEncoding = [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
          ./repro
          ./repro -Djava.file.encoding=UTF-8

      - name: Upload repro.exe
        if: matrix.distribution == 'graalvm'
        uses: actions/upload-artifact@v4
        with:
          name: repro-exe
          path: repro.exe
